ui/js/vendor/langmap.js

I very much assume "Yiddish (German)" is supposed to mean "Yiddish (Germany)", as Yiddish and German are two separate languages and given the DE country code in yi-DE .

Error (Yiddish)

---

lib/coins/btc.js

Operator reports that some wallets use QR codes with `Bitcoin:` as the URI, resulting in:
```
2018-01-31T02:08:09.842Z LOG new brain state: scanAddress
2018-01-31T02:08:18.943Z LOG DEBUG55: Bitcoin:1[redacted]
2018-01-31T02:08:18.945Z LOG DEBUG16: [main] Bitcoin
2018-01-31T02:08:18.967Z LOG Error: Invalid checksum
at Object.decode (/opt/apps/machine/lamassu-machine/node_modules/bs58check/index.js:46:23)
at validate (/opt/apps/machine/lamassu-machine/lib/coins/btc.js:26:27)
at Object.parseUrl (/opt/apps/machine/lamassu-machine/lib/coins/btc.js:12:8)
at Object.parseUrl (/opt/apps/machine/lamassu-machine/lib/coins/utils.js:53:17)
at /opt/apps/machine/lamassu-machine/lib/scanner.js:138:37
at Camera.cam.stop (/opt/apps/machine/lamassu-machine/lib/scanner.js:96:18)
```
Best to accept either …

Accept either bitcoin: or Bitcoin: URIs

---

lib/coins/bch.js
package.json

Apart from UI considerations due to the longer address extending across screen elements, this will establish CashAddr support on the machine-side.

 Parse, generate, validate CashAddr format

---

lib/brain.js

I previously added an exception [here](https://github.com/lamassu/lamassu-machine/pull/116#discussion-diff-193978372R2572)
Actually I'm not sure if it's the proper way to handle this.
If the physical dispense is successful we transit from fiatComplete to goodbye screen but in the middle there is a delay of 1 minute, in which a user can start another transaction.
So in this case it make sense to check for:
```
const doComplete = this.state === 'fiatComplete' && this.tx.id === txId
```
To decide whenever to show or not the goodbye screen.
Anyway I think we should move the `emit('billDispenserCollected')` up before the delay so that we always run that, regardless the above check

cash dispenser bugfix

---

lib/brain.js

I'm not sure if the correct name should be `hasNewScanBay` or `hasOldScanBay`

lamp scan bay naming fix

---

lib/brain.js
lib/f56/f56-dispenser.js
lib/mocks/billdispenser.js
lib/puloon/puloon-dispenser.js
lib/puloon/puloonrs232.js

Following my comments here https://trello.com/c/zW9TJcIm/514-dispenser-errors-arent-recorded-in-cashout-tables
I think the issue is that the error logged as:
```
dispenser response
{ code: 82,
name: 'dispense',
err: 88,
bills: [ { dispensed: 0, rejected: 0 }, { dispensed: 0, rejected: 0 } ] }
```
is not correctly propagated

Puloon dispenser error fix

---

lib/pairing.js

A invlid QR code was throwing a completly unrelated error because of
invalid chars on the generated URL.
Exceptions are now logged on the console with a friendly error for the
operator.

Added error handling on pairing errors

---

lib/brain.js

Declining to verify ID during a cash_in was causing the machine to
hang indefinedely.

Stop machine from hanging when verifying ID

---

lib/brain.js

The machine was counting a bill that gets returned to the user when
asking for ID verification on cash_in

Stop overcrediting after ID verification

---

lib/brain.js
lib/scanner.js

Machine could get restarted when canceling scanAddress screen. Because
of the polling on the camera code, cam.stop() could be called multiple
times causing a c error to be thrown.

Camera restarts machine fix

---

ui/src/app.js

When there are only two languages the text was not translating on change.
Previously only changed the text when coming from a languages screen.

Fix translation text of buy/sell button

---

lib/brain.js

The correct flow is now:
```
2018-11-25T07:13:13.540Z LOG new brain state: chooseCoin
2018-11-25T07:13:14.357Z LOG new brain state: registerPhone
2018-11-25T07:13:16.128Z LOG new brain state: waiting
2018-11-25T07:13:16.635Z LOG new brain state: securityCode
2018-11-25T07:13:18.362Z LOG new brain state: scanAddress
```

Fix returnState for smsCompliance at 0$

---

lib/dispense-generator.js
lib/f56/f56-rs232.js

This should now propagate the `statusCode` and properly log the F56 protocol error code. According to the F56 D-LEVEL spec, the error code lives at bytes 3 and 4 in the response frame.

Identify F56 error code in message log

---

deploy/commands/reboot.js
lib/trader.js

This reboot script will now handle ssuboard's lamassu-machine and lamassu-browser reboot through `supervirsorctl`.
Also added a readability improvement, regarding date handling, that was missing from #267.

Update reboot script to handle ssuboard systems

---

deploy/codebase/updateinit.js

The update package might carry invalid configurations for the fields related with the bill dispenser and bill validator. This will consume their current working configurations into the update's `package_config.json` file before deploying it in the system.

Adjust the update configuration of bill dispenser and validator

---

tools/nipponPrinterTests.js

This test script should print a welcoming message and a QR code for https://lamassu.is, using the serial interface for the Nippon NP-2511D-2 kiosk printer.
It should be executed like `sudo node nipponPrinterTests.js`.  
It can take two parameters: `--dev` and `--str`. The first will select a different serial port than the default one (`/dev/ttyJ5`) and the second let the user set the content of the QR code.

Add test script for the Nippon's kiosk printer

---

lib/brain.js
ui/src/app.js

Jquery.html() has a small delay on mounting the text to the dom.
This is barely noticeble in dev but in prod we're getting failures

Add small delay on terms and conditions

---

software_config.json

This had been present in a DO version of this file used in the build process, but our repo's version should be used instead.

Extend scanner timeout

---

deploy/codebase/updateinit.js
deploy/reboot-uni/updatescript.js

We should preserve both the validator type (*i.e.*, `cashflowSc`) as well as its mount point during updates.

deploy package changes

---

hardware/codebase/upboard/device_config.json
tools/nipponPrinterTests.js

Printer should stay at J4 and bill validator at J5
physical proximity reasons

Change device mapping

---

deploy/codebase/build.sh

Otherwise, error as mock-cam.js had been removed.

Remove mock-cam from package build

---

ui/src/app.js

In case there is 0 or more than one possible views matching the name of a new view, error message is printed on JS console. This makes it easier to debug the UI because you'll get an error and not just a white screen only.

Add UI error logging for cases when no unique view is found

---

lib/configuration.js
lib/mocks/scanner.js

This PR has two related but distinct patches:
* Allow reading mock camera QR code data dynamically from a file or FIFO instead of static content. Makes it easier to debug UI state transformations because app is not needed to restart while testing many QR codes.
* Make mock camera behave more like a real camera by keeping the "opened" state consistent. Without this patch `isOpened()` returns always true, making some operations to fail on mock camera.

Mock camera improvements

---

hardware/codebase/ssuboard/device_config.json

1280x960 is not a supported resolution for this camera

Fix resolution for front facing camera

---

INSTALL.md

Fixed the lamassu-machine first run command by moving the totem string to the right location, which is after --mockPair

fix: moved <totem-from-admin> param on l-m execution to the right place

---

deploy/purge-logs/updatescript.js
deploy/show_log/updatescript.js

Clear all logs with `purge-logs` to set a baseline and reduce log archive size. (Helpful as `lamassu-browser` and others don't have timestamps, thus we should clear old entries.)
Increase log archive size for `show_log`, as we've run into longer archives that are corrupted upon upload.

chore: increase log archive size

---

lib/mocks/scanner.js

Mock camera cancellation callback should return *null*s instead of *undefined* to behave identically as the real camera.
Also, changed reading of mock QR codes to read file async to support reading from FIFOs or other blocking devices so that cancellation works, too.

Mock camera fixes

---

deploy/codebase/updateinit.js
deploy/reboot-749/build.sh
deploy/reboot-749/updatescript.js

`chromium-browser` and `start-chrome` don't reliably restart as part of the codebase update. Moving to a new reboot script instead.

fix: support v7.4.9 update process

---

lib/id003/id003.js
lib/logs.js
shell.nix

- only look at files ending in .log
- rotate files larger than 1MB to be removed
- fix a bug where id003 was calling for status simultaneously and creating error logging loop

fix: improve logs handling

---

deploy/codebase/updateinit.js

Fixes issue with updating the Douro II, where `cryptomatModel` was overwritten, as lamassu-watchdog only conveys the platform on the ssuboard, rather than platform + model as it does with UPboards.
For UPboards, a further safeguard against overwriting.

fix: preserve cryptomatModel upon update
