README.md
figured this one out - may help others
=> install instruction for Mac OS X local testing & development

ui/src/app.js
Renders ISK instead of Ikr on machine display, for example.
=> Fix for ISO-standard currency display

.gitignore, README.md, lib/brain.js, lib/trader.js, lib/tx.js, ui/src/app.js, ui/start.html
Relies on https://github.com/lamassu/lamassu-server/pull/118
=> Terms screen added

lib/brain.js
```
2018-06-19T00:25:15.731Z LOG new brain state: registerPhone
2018-06-19T00:25:18.411Z LOG new brain state: waiting
2018-06-19T00:25:18.519Z LOG fiatError Error: Fatal: unsupported coin: undefined
at Brain.exceedsZeroConf (/Users/fabio/Documents/lu/lamassu-machine/lib/brain.js:2428:20)
at Brain._dispenseUpdate (/Users/fabio/Documents/lu/lamassu-machine/lib/brain.js:2624:29)
at Brain.smsFlowHandleReturnState (/Users/fabio/Documents/lu/lamassu-machine/lib/brain.js:1267:17)
at trader.phoneCode.then.catch.err (/Users/fabio/Documents/lu/lamassu-machine/lib/brain.js:1198:14)
at <anonymous>
at process._tickCallback (internal/process/next_tick.js:182:7)
2018-06-19T00:25:18.519Z LOG new brain state: fiatError
2018-06-19T00:25:19.650Z LOG new brain state: pendingIdle
```
=> sms compliance unhandled error

lib/brain.js
https://trello.com/c/9277wdW9/464-if-bad-twilio-credentials-requires-l-m-restart
=> SMS flow error handling

lib/brain.js
https://trello.com/c/bdMNpVxq/549-blocking-compliance-tiers
=> Blocking compliance tiers fix

lib/brain.js, ui/css/main.css, ui/src/app.js, ui/start.html
While debugging https://trello.com/c/RQs2QrwX/536-dispense-error-following-successful-dispense I came up with those fixes that aren't directly related
=> minor fixes

lib/brain.js, lib/trader.js, ui/start.html
https://trello.com/c/xDhnNOaq/572-blocked-customer-flow-on-cash-out-invokes-cash-in-screens
=> cashout blocked user flow fix

lib/brain.js
Here are the fixes as suggested in https://trello.com/c/aNqpwqze/547-smsflowhandlereturnstate-logic-error
=> SMS compliance flow fix

lib/brain.js
The linked commit caused unwanted changes:
https://github.com/lamassu/lamassu-machine/pull/137/commits/18cc3ac075aa0f342d03921ab07e6f5ba86ec591
=> Stop showing choose fiat screen during redemption

.vscode/launch.json, lib/brain.js, ui/src/app.js, ui/start.html
Some user actions can impair redepmtion or cancel transactions, this
screen was added to get a confirmation from the user.
=> Add "Are you sure?" screen

lib/puloon/puloon-dispenser.js, lib/puloon/puloonrs232.js
@joshmh Added `retrySentCommand` timeout set to 50ms. Timeout is cleared if ACK is received. Is this what you had in mind?
=> Fix nosoh bug

lib/brain.js
When going idle the are you sure screen has to perform a couple of steps
before calling the '_idle' function.
=> Fix 'are you sure' screen idle process

lib/error.js, lib/trader.js, package-lock.json, package.json
Also bumped stardand version to match with l-s
=> Improve transaction errors

lib/trader.js
Milestone: 7.3.x Crafty Chnemu
=> Add error logs on `syncLogs` method

lib/coins/btc.js, lib/coins/dash.js, lib/coins/ltc.js, lib/coins/validators/index.js, lib/coins/zec.js, package-lock.json, package.json, test/unit/test-crypto-validation.js
=> Add support for bech32 BTC address, unit test validators

lib/compliance/parsepdf417-us.js
Milestone: 7.3.x Crafty Chnemu
=> fix pdf417 for colorado

hardware/codebase/aaeon/device_config.json
Reverting 8ca16f6e0f10caa9f52871565ed5d532bdaad6ec
=> partial revert 8ca16f6e0f10caa9f52871565ed5d532bdaad6ec

lib/dispense-generator.js, lib/dispense-optimizer.js, test/unit/test-optimize-batch.js, ui/src/app.js, ui/start.html
Note: this is to be merged after https://github.com/lamassu/lamassu-machine/pull/195, three of the commits are from it.
=> Hide batch counter single dispense

lib/brain.js, lib/dispense-generator.js, lib/dispense-optimizer.js, test/unit/test-optimize-batch.js, ui/src/app.js, ui/start.html
Note: this is to be merged after https://github.com/lamassu/lamassu-machine/pull/198 and https://github.com/lamassu/lamassu-machine/pull/195, four of the commits are from them.
=> Fix dispense error handling

os-cleanup.sh
Added cleanup script for most of required steps
=> add os cleanup bash script

package.json, tools/led-test.js, tools/printer.js, ui/css/main-1080.css
This pull request shall contain the last fixes and additions that will ship with the first Sintras:
- Test script for the Zebra printer.
- Fixes for the 1080p resolution.
_Work in progress..._
=> Updates for Sintra image

hardware/system/ssuboard/supervisor.txt, tools/printer.js
- Improved printer's test script
- Replaced Firefox by Surf in ssuboard's supervisor configuration
=> More updates for Sintra image

lib/brain.js, lib/scanner.js, ui/src/app.js
Clean up was running twice leaving the machine on a unwanted state.
ID Card Photo callback was not being called in case of cancel.
=> Fix ID Card Photo cancel flow

lib/f56/bills.js
=> Additional F56 currencies

deploy/bb-debs/build.sh, deploy/bb-debs/updatescript.js
For remote update script to `apt` install required dependencies for v7.2.
=> Add build script for bb-debs update

lib/update/updater.js
Allows deployment of `bb-debs` package following push of `codebase-7.2.1`'s update.tar and `updater.js` restart.
Via @littlenaut.
=> set updater.js keepAlive

lib/update/updater.js
Some fixes introduced in PR #201 were missing from the dev branch. This PR serves to add them.
=> Merge remaining changes from #201 into dev

lib/brain.js, ui/src/app.js
Superseds https://github.com/lamassu/lamassu-machine/pull/256
=> Only show wifi screen on douro

software_config.json
Otherwise, easy to miss this screen if focusing on one's phone.
=> Extend invalidAddressTimeout

lib/brain.js, lib/coins/btc.js, lib/coins/utils.js, lib/kioskPrinter.js, lib/mocks/kioskPrinter.js, lib/trader.js, package-lock.json, package.json, ui/css/main.scss, ui/css/text-content-sizes.scss, ui/html/choose-fiat.html, ui/html/deposit.html, ui/html/insert-bills.html, ui/html/printer.html, ui/html/register-phone.html, ui/html/scan-address.html, ui/html/scan-id.html, ui/html/scan-photo.html, ui/html/security-code.html, ui/html/wifi.html, ui/src/app.js
Supersedes https://github.com/lamassu/lamassu-machine/pull/254
=> WIP: Paper wallet printing

lib/dispense-generator.js, lib/f56/f56-rs232.js
This is a continuation of #274.
This objective now is to also propagate the report to the error log that is sent to the server.
=> Identify F56 error code in message log (reprise)

deploy/cc-watchdog/build.sh, deploy/cc-watchdog/updatescript.js, watchdog.js
An update to watchdog's timeout is needed prior to pushing Crafty Chnemu's package.
=> Create cc-watchdog package

INSTALL-NIX.md, INSTALL.md, lib/brain.js
Hardware setup misrecognized computer as a Nexus 7.
=> fix: add debug board flag

INSTALL-NIX.md
troubleshooting info for serialport bindings; nix-sell locale issue and node-sass issue
=> docs: troubleshooting infos

package-lock.json, package.json
Reverts lamassu/lamassu-machine#442
=> Revert "v7.5.5"

lib/brain.js, lib/printer/loader.js, test/unit/test-brain-batch-dispense.js
I think I finally understood how batchDispense is suposed to work and have writen a couple of (failling) tests for the BillDispense.factory mock.
This is a WIP so I will be pushing new commits and may be even rewriting my old ones
=> test: brain batch dispense

hardware/codebase/upboard/gaia/device_config.json
Reverts lamassu/lamassu-machine#515
=> Revert "fix: mounting position for puloon dispenser"

lib/brain.js, lib/trader.js
=> fix: 'Shutdown' admin button not shutting down machine
